# Generated by Django 5.2.11 on 2026-04-01 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type_dimension', models.CharField(choices=[('temporelle', 'Temporelle'), ('categorielle', 'Catégorielle'), ('territoriale', 'Territoriale'), ('autre', 'Autre')], default='categorielle', max_length=50)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='PageIndicateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('sous_titre', models.CharField(blank=True, max_length=255)),
                ('chapeau', models.TextField(blank=True)),
                ('texte_methodologique', models.TextField(blank=True)),
                ('texte_source', models.TextField(blank=True)),
                ('date_mise_a_jour', models.DateField(blank=True, null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordre', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='PopulationStatistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Thematique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordre', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='Graphique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('sous_titre', models.CharField(blank=True, max_length=255)),
                ('type_graphique', models.CharField(choices=[('ligne', 'Ligne'), ('barres', 'Barres'), ('colonnes', 'Colonnes'), ('barres_empilees', 'Barres empilées'), ('colonnes_empilees', 'Colonnes empilées'), ('aire', 'Aire'), ('camembert', 'Camembert'), ('anneau', 'Anneau')], max_length=50)),
                ('titre_axe_x', models.CharField(blank=True, max_length=255)),
                ('titre_axe_y', models.CharField(blank=True, max_length=255)),
                ('titre_axe_y_secondaire', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('champ', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('empile', models.BooleanField(default=False)),
                ('axe_y_secondaire_actif', models.BooleanField(default=False)),
                ('legende_visible', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('dimension_x', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graphiques_x', to='dashboard.dimensionanalyse')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphiques', to='dashboard.pageindicateur')),
                ('population', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graphiques', to='dashboard.populationstatistique')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ImportDonnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='imports/')),
                ('statut', models.CharField(choices=[('depose', 'Déposé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('erreur', 'Erreur')], default='depose', max_length=20)),
                ('rapport', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.pageindicateur')),
            ],
        ),
        migrations.CreateModel(
            name='SerieGraphique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalite_code', models.CharField(blank=True, max_length=100)),
                ('code', models.SlugField()),
                ('libelle', models.CharField(max_length=255)),
                ('type_serie', models.CharField(blank=True, max_length=50)),
                ('couleur', models.CharField(blank=True, max_length=20)),
                ('axe', models.CharField(choices=[('gauche', 'Axe gauche'), ('droite', 'Axe droite')], default='gauche', max_length=10)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.dimensionanalyse')),
                ('graphique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='dashboard.graphique')),
            ],
            options={
                'ordering': ['ordre', 'id'],
                'unique_together': {('graphique', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_x', models.CharField(max_length=100)),
                ('libelle_x', models.CharField(max_length=255)),
                ('ordre_x', models.IntegerField(default=0)),
                ('valeur', models.FloatField(blank=True, null=True)),
                ('valeur_formatee', models.CharField(blank=True, max_length=255)),
                ('infobulle', models.TextField(blank=True)),
                ('metadonnees', models.JSONField(blank=True, default=dict)),
                ('ordre', models.IntegerField(default=0)),
                ('graphique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='dashboard.graphique')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='dashboard.seriegraphique')),
            ],
            options={
                'ordering': ['ordre_x', 'id'],
            },
        ),
        migrations.AddField(
            model_name='pageindicateur',
            name='thematique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='dashboard.thematique'),
        ),
        migrations.CreateModel(
            name='ModaliteDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('libelle', models.CharField(max_length=255)),
                ('ordre', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalites', to='dashboard.dimensionanalyse')),
            ],
            options={
                'ordering': ['dimension', 'ordre'],
                'unique_together': {('dimension', 'code')},
            },
        ),
    ]
