# Generated by Django 5.2.11 on 2026-04-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphique',
            name='icone',
            field=models.FileField(blank=True, null=True, upload_to='graphiques_icones/'),
        ),
        migrations.AddField(
            model_name='graphique',
            name='texte_valeur_cle',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='graphique',
            name='type_graphique',
            field=models.CharField(choices=[('ligne', 'Ligne'), ('barres', 'Barres'), ('colonnes', 'Colonnes'), ('barres_empilees', 'Barres empilées'), ('colonnes_empilees', 'Colonnes empilées'), ('aire', 'Aire'), ('camembert', 'Camembert'), ('anneau', 'Anneau'), ('valeur_cle', 'Valeur clé')], max_length=50),
        ),
    ]
