# Generated by Django 5.2.10 on 2026-04-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_graphique_icone_graphique_texte_valeur_cle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriegraphique',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='graphique',
            name='dimension_x',
        ),
        migrations.RemoveField(
            model_name='importdonnees',
            name='page',
        ),
        migrations.RemoveField(
            model_name='graphique',
            name='population',
        ),
        migrations.RemoveField(
            model_name='seriegraphique',
            name='modalite_code',
        ),
        migrations.DeleteModel(
            name='ModaliteDimension',
        ),
        migrations.DeleteModel(
            name='DimensionAnalyse',
        ),
        migrations.DeleteModel(
            name='ImportDonnees',
        ),
        migrations.DeleteModel(
            name='PopulationStatistique',
        ),
    ]
