# Generated by Django 5.2.11 on 2026-04-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_refactor_thematique_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphique',
            name='axe_y_secondaire_actif',
        ),
        migrations.RemoveField(
            model_name='graphique',
            name='empile',
        ),
        migrations.RemoveField(
            model_name='graphique',
            name='titre_axe_y_secondaire',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='ordre',
        ),
        migrations.RemoveField(
            model_name='seriegraphique',
            name='axe',
        ),
        migrations.RemoveField(
            model_name='seriegraphique',
            name='type_serie',
        ),
        migrations.AlterField(
            model_name='graphique',
            name='code',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='ordre_x',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seriegraphique',
            name='code',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='thematique',
            name='code',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='thematique',
            table=None,
        ),
    ]
