"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from django.templatetags.static import static
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+ulfb-csr%u62x_e0n8e9*fo2_g^z4*zt&px*3r7%h6vynvpt$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

LANGUAGES = [
    ('fr', 'Français'),
]

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/



STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


def _unfold_logo(_request):
    return static("icons/logo_ssmsi_svg.svg")


def _unfold_styles(_request):
    return static("css/admin_ssmsi.css")


UNFOLD = {
    "SITE_TITLE": "SSMSI Admin",
    "SITE_HEADER": "Interstats",
    "SITE_SUBHEADER": "Administration des actualites et indicateurs",
    "SITE_LOGO": {
        "light": _unfold_logo,
        "dark": _unfold_logo,
    },
    "SITE_ICON": {
        "light": _unfold_logo,
        "dark": _unfold_logo,
    },
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Saisie des contenus",
                "separator": False,
                "collapsible": False,
                "items": [
                    {
                        "title": "1. Thematiques",
                        "icon": "topic",
                        "link": reverse_lazy("admin:dashboard_thematique_changelist"),
                    },
                    {
                        "title": "2. Graphiques",
                        "icon": "insert_chart",
                        "link": reverse_lazy("admin:dashboard_graphique_changelist"),
                    },
                    {
                        "title": "3. Import XLSX",
                        "icon": "upload_file",
                        "link": "/admin/import/",
                    },
                    {
                        "title": "4. Statistiques",
                        "icon": "dashboard",
                        "link": "/admin/statistiques/",
                    },
                ],
            },
            {
                "title": "Administration",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Utilisateurs",
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                ],
            },
        ],
    },
    "STYLES": [_unfold_styles],
    "COLORS": {
        "base": {
            "50": "#f7f9fc",
            "100": "#eef2f7",
            "200": "#dde5ef",
            "300": "#c2cfdf",
            "400": "#9eacc0",
            "500": "#7b8798",
            "600": "#616d7d",
            "700": "#4f5a6a",
            "800": "#374151",
            "900": "#1f2937",
            "950": "#111827",
        },
        "primary": {
            "50": "#eef3fb",
            "100": "#dde8f6",
            "200": "#c2d6ec",
            "300": "#93b4da",
            "400": "#6b96ca",
            "500": "#4f80bf",
            "600": "#3c4d88",
            "700": "#354578",
            "800": "#2e3a64",
            "900": "#253050",
            "950": "#182039",
        },
        "font": {
            "subtle-light": "#667085",
            "subtle-dark": "#c2cfdf",
            "default-light": "#344054",
            "default-dark": "#dde5ef",
            "important-light": "#182230",
            "important-dark": "#f8fafc",
        },
    },
}

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
